apiVersion: v1
kind: Service
metadata:
  name: cards-backend
  labels:
    app: cards-backend
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"5000":"cards-backendconfig"}}'
spec:
  type: NodePort
  selector:
    app: cards-backend
  ports:
  - port: 5000
    protocol: TCP
    name: cards-backend-port
---
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: cards-backendconfig
spec:
  timeoutSec: 7200
  connectionDraining:
    drainingTimeoutSec: 3600
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cards-backend-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "cards-backend"
spec:
  backend:
    serviceName: cards-backend
    servicePort: 5000