apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cards-backend
  template:
    metadata:
      labels:
        app: cards-backend
    spec:
      containers:
        - name: flask
          image: "gcr.io/optimum-pier-280005/github.com/zachcalvert/cards-backend:fcf2d30f72fdb4ec44fa8f6fcfc1c4f90e41f286"
          env:
            - name: "REDISHOST"
              value: "localhost"
          ports:
            - name: http
              containerPort: 5000
        - name: redis
          image: redis
          ports:
            - containerPort: 6379