apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: cribbage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cards-backend
  template:
    metadata:
      labels:
        app: cards-backend
    spec:
      containers:
        - name: flask
          image: "gcr.io/optimum-pier-280005/github.com/zachcalvert/cribbage-server:c949c29193cd8515c114d93f25213b2f4f68a187"
          env:
            - name: "REDISHOST"
              value: "localhost"
          ports:
            - name: http
              containerPort: 5000
        - name: redis
          image: redis
          ports:
            - containerPort: 6379