apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cards-backend
  template:
    metadata:
      labels:
        app: cards-backend
    spec:
      containers:
        - name: flask
          image: "gcr.io/optimum-pier-280005/github.com/zachcalvert/cards:backend-8dcbaf88b5877b53dc5a1a2ee6d6741f8902995f"
          env:
            - name: "REDISHOST"
              value: "localhost"
          ports:
            - name: http
              containerPort: 5000
        - name: redis
          image: redis
          ports:
            - containerPort: 6379