apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: cribbage
  labels:
    app: cribbage-backend
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"5000":"cribbage-backendconfig"}}'
spec:
  type: ClusterIP
  selector:
    app: cribbage-backend
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: backend-port
---
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: cribbage-backendconfig
  namespace: cribbage
spec:
  timeoutSec: 7200
  connectionDraining:
    drainingTimeoutSec: 3600
