apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cribbage-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
      - cribbage.live
      secretName: cribbage-live-tls
  rules:
  - host: cribbage.live
    http:
      paths:
      - path: /
        backend:
          serviceName: frontend-service
          servicePort: frontend-port
      - path: /socket.io
        backend:
          serviceName: backend-service
          servicePort: backend-port
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: zach@cribbage.live
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - selector: {}
      http01:
        ingress:
          class: nginx