apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: cribbage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cards-frontend
  template:
    metadata:
      labels:
        app: cards-frontend
    spec:
      containers:
        - name: react
          image: "gcr.io/optimum-pier-280005/github.com/zachcalvert/cribbage-client:c949c29193cd8515c114d93f25213b2f4f68a187"
          ports:
            - containerPort: 80