apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cards-frontend
  template:
    metadata:
      labels:
        app: cards-frontend
    spec:
      containers:
        - name: react
          image: "gcr.io/optimum-pier-280005/github.com/zachcalvert/cards-client:55ebbab97e640642dba47d418ba48dd6f79e5c9b"
          ports:
            - containerPort: 80